workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

build_files:
  needs: []
  image:
    name: electronuserland/builder:wine
  script:
    - npm install -g npm@8
    - npm install
    - VERSION="1.$(date +%Y%m%d.1%H%M%S)"
    - echo "$VERSION" > src/main/version.txt
    - npm run build
    - npx electron-builder --win
    - echo "VERSION=$VERSION" > build.env
  artifacts:
    expire_in: 1 week
    paths:
      - "dist/OscGoesBrrr-setup.exe"
    reports:
      dotenv: build.env

release:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo 'running release_job'
  needs:
    - job: build_files
      artifacts: true
  release:
    name: 'OscGoesBrrr $VERSION'
    description: This is a release of OscGoesBrrr. Click 'Download Windows Zip' above to download!
    tag_name: '$VERSION'
    assets:
      links:
        - name: 'Download Windows Zip'
          url: '${PACKAGE_URL}'
          filepath: '/OscGoesBrrr.zip'

bump_autoupdater:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - job: build_files
      artifacts: true
    - release
  image: curlimages/curl
  script:
    - >
      echo "$ASAR_URL"

      curl
      --silent --show-error
      --request PUT
      --data "url=$ASAR_URL"
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      "https://gitlab.com/api/v4/projects/vrcfury%2foscgoesbrrr/releases/autoupdater/assets/links/868919"

      curl
      --silent --show-error
      --header 'Content-Type: application/json'
      --request PUT
      --data '{ "description": "version='"$VERSION"'" }'
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      "https://gitlab.com/api/v4/projects/vrcfury%2foscgoesbrrr/releases/autoupdater"
