branches:
  - main
  - name: "!(main)"
    prerelease: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - breaking: true
          release: major
  - - "@semantic-release/exec"
    - analyzeCommitsCmd: echo minor
      verifyReleaseCmd: |
        echo "version=${nextRelease.version}" >> "$GITHUB_OUTPUT"
        echo "tagName=v${nextRelease.version}" >> "$GITHUB_OUTPUT"
