minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@ttsc/*'
  - ttsc
allowBuilds:
  '@parcel/watcher': false
  '@serialport/bindings-cpp': false
  '@swc/core': false
  electron-winstaller: false
  esbuild: false
  native-reg: false
